name: JMAPROSPECTING
favicon: null
layout_spectrum: 0.7221201441716403
typography_spectrum: 0.6768508569803089
title: COLORADO GOLD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.792719894554466
  lightness: 0.7358091147616506
  saturation: 0.5851163484621793
  rhythmicContrast: 0.7992903920821846
purpose: []
